services:
    app:
        build: .
        container_name: finance-app
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        extra_hosts:
            - "host.docker.internal:host-gateway"

    mysql:
        image: mysql:8.0
        container_name: finance-db
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: finance
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    mailpit:
        image: 'axllent/mailpit:latest'
        container_name: finance-mail
        ports:
            - '1025:1025' # Porta do servidor SMTP (onde o Laravel envia)
            - '8025:8025' # Interface Web (onde você visualiza os e-mails)
        networks:
            - default
            
volumes:
    mysql_data:
